version: '2'

services:
  camunda:
    image: camunda/camunda-bpm-platform
#    volumes:
#      - ./webapps/:/camunda/webapps/
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - 8080:8080

  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=sEcrEt
      - POSTGRES_USER=camunda
    volumes:
      - ./.data/db:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
